import { writeFile, readFile } from "node:fs/promises";
import { join, basename } from "node:path";
import { GitManager, createAgent } from "@orbit/core";
import type { AIProvider } from "@orbit/core";

/**
 * Analyze recent commits and PRs to learn the user's coding style.
 * Writes a style-guide.md to the context folder.
 * Should be run periodically (e.g., weekly) or on demand via /orbit learn-style.
 */
export async function learnCodeStyle(
  workspaceRoots: string[],
  contextFolder: string,
  anthropicApiKey?: string,
  aiProvider?: AIProvider,
): Promise<string> {
  // Gather recent diffs across all repos
  const diffs: { repo: string; diff: string }[] = [];

  for (const root of workspaceRoots) {
    const git = new GitManager(root);
    const repos = await git.discoverRepos().catch(() => []);

    for (const repo of repos) {
      try {
        // Get last 20 commits' diffs (last 2 weeks)
        const { execFile } = await import("node:child_process");
        const { promisify } = await import("node:util");
        const exec = promisify(execFile);

        const since = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString();
        const { stdout } = await exec("git", [
          "log", `--since=${since}`, "--oneline", "--no-merges",
          "--diff-filter=M", "-p", "-10",  // last 10 modified-file diffs
          "--", "*.ts", "*.tsx", "*.js", "*.jsx",
        ], { cwd: repo, maxBuffer: 5 * 1024 * 1024 });

        if (stdout.trim()) {
          diffs.push({ repo: basename(repo), diff: stdout.slice(0, 15000) });
        }
      } catch {}
    }
  }

  if (diffs.length === 0) {
    return "No recent code changes found to analyze.";
  }

  // Send to Claude for analysis
  const claude = createAgent(aiProvider ?? "claude", anthropicApiKey);
  const allDiffs = diffs.map((d) => `=== ${d.repo} ===\n${d.diff}`).join("\n\n").slice(0, 40000);

  const result = await claude.run(
    `Analyze these recent git diffs from a developer and extract their coding style patterns. Focus on CONSISTENT patterns, not one-off choices.

RECENT CODE CHANGES:
${allDiffs}

Extract these specific patterns:

===STYLE_GUIDE===
## Naming Conventions
- Variables: (camelCase/snake_case, prefixes like is/has for booleans, etc.)
- Functions: (verb-first, async naming patterns, etc.)
- Components: (PascalCase, naming patterns)
- Files: (kebab-case/camelCase, suffix patterns like .service.ts, .utils.ts)

## Code Structure
- Import ordering (third-party first? grouped by type?)
- Export style (named exports, default exports, barrel files?)
- Function style (arrow functions vs function declarations, when each is used)
- Error handling patterns (try/catch style, error types, fallback patterns)

## TypeScript Patterns
- Type vs Interface preference
- Type annotation style (explicit return types? inline vs extracted?)
- Null handling (optional chaining, nullish coalescing, assertions)
- Generic patterns

## Component Patterns (if React/frontend code found)
- Component structure (hooks at top? early returns?)
- State management approach
- Event handler naming (handleX, onX)
- Prop patterns

## Commit Messages
- Format (conventional commits? prefixes?)
- Tense (present/past)
- Length and detail level

## Other Patterns
- Comment style (when and how they comment)
- Logging patterns
- Test patterns (if any)
===END_STYLE_GUIDE===

Only include sections where you found clear, repeated patterns. Skip sections where there's not enough data. Be specific — give examples from the actual code.`,
    process.cwd(),
  );

  // Extract style guide
  const startIdx = result.output.indexOf("===STYLE_GUIDE===");
  const endIdx = result.output.indexOf("===END_STYLE_GUIDE===");
  let styleGuide: string;

  if (startIdx !== -1) {
    styleGuide = result.output.slice(
      startIdx + "===STYLE_GUIDE===".length,
      endIdx === -1 ? undefined : endIdx,
    ).trim();
  } else {
    styleGuide = result.output.slice(0, 5000);
  }

  // Write to context folder
  const filePath = join(contextFolder, "style-guide.md");
  const content = [
    `# Code Style Guide`,
    `_Auto-generated by Orbit from recent commits — ${new Date().toISOString().split("T")[0]}_`,
    ``,
    styleGuide,
  ].join("\n");

  await writeFile(filePath, content);

  return `Style guide updated with patterns from ${diffs.length} repo(s).`;
}

/**
 * Get the current style guide content (for including in Claude prompts).
 */
export async function getStyleGuide(contextFolder: string): Promise<string> {
  try {
    return await readFile(join(contextFolder, "style-guide.md"), "utf-8");
  } catch {
    return "";
  }
}
